// client/src/app/(pages)/nba/page.tsx
import "./nba.css";
import LeadersBox from "./_components/statbox/StatBox";
import Link from "next/link";
import Button from "@/components/ui/Button";
import { MoveRight } from "lucide-react";
import NbaGame from "./_components/games-scores/NbaGame";
import GamesToday from "./_components/games-scores/GamesToday";

export default function Nba() {
  return (
    <main className="nba-page">
      <section className="nba-today wrapper">
        <h3>NBA Games & Scores</h3>
        <GamesToday />
      </section>
      <section className="nba-page-leaders wrapper">
        <h3>NBA Leaders</h3>
        <LeadersBox header="Points per game" stat="PTS" />
        <Link href="/nba/leaders" className="nba-page-link">
          <Button className="btn-outline btn-with-icon">
            View All Leaderboards
            <MoveRight size={14} className="btn-icon" />
          </Button>
        </Link>
      </section>
    </main>
  );
}

// sveltekit-client/src/routes/nba/+page.svelte
<script lang="ts">
	import Button from '$lib/components/ui/Button.svelte';
	import { MoveRight } from '@lucide/svelte';
</script>

<main class="nba-page">
	<section class="nba-today wrapper">
		<h1>NBA</h1>
		<h2>NBA Games & Scores</h2>
		<!-- <GamesToday /> -->
	</section>
	<section class="nba-page-leaders wrapper">
		<h2>NBA Leaders</h2>
		<!-- <LeadersBox header="Points per game" stat="PTS" /> -->
		<a href="/nba/leaders" class="nba-page-link">
			<Button class="btn-outline btn-with-icon">
				View All Leaderboards
				<MoveRight size={14} class="btn-icon" />
			</Button>
		</a>
	</section>
</main>

<style>
	.nba-page {
		display: flex;
		flex-direction: column;
		width: 100%;
		gap: 2rem;
		padding-bottom: 2rem;

		& h1 {
			align-self: center;
		}

		& h2 {
			font-size: 2rem;
			letter-spacing: 0;
		}
	}

	.nba-today {
		padding-top: 2rem;
	}

	.nba-today,
	.nba-page-leaders {
		display: flex;
		flex-direction: column;
		gap: 1rem;
	}

	.nba-page-link {
		width: max-content;
	}
</style>
