// client/src/app/(pages)/nba/_components/games-scores/NbaTodayStatus.tsx
import "./NbaTodayStatus.css";
import { formattedDate, formatGameTime } from "@/lib/utils/format";
import { NbaToday } from "@/lib/utils/types/nba";

type NbaTodayStatusProps = {
  game: NbaToday;
};

export default function NbaTodayStatus({ game }: NbaTodayStatusProps) {
  return (
    <div className="nba-today-gamestatus">
      {game.gameStatus === 1 ? (
        <>
          <p className="game-date">{formattedDate(game)}</p>
          <h3>{formatGameTime(game.gameTimeUTC, game.gameStatusText)}</h3>
        </>
      ) : (
        <h3>{game.gameStatusText}</h3>
      )}
    </div>
  );
}

// sveltekit-client/src/routes/nba/components/NbaTodayStatus.svelte
<script lang="ts">
	import { NBA_GAME_STATUS } from '$lib/constants/nba';
	import type { NbaGame } from '$lib/types/nba';
	import { formatGameTime } from '$lib/utils/format';

	let { game }: { game: NbaGame } = $props();
</script>

<div class="nba-today-gamestatus">
	{#if game.gameStatus === NBA_GAME_STATUS.NOT_STARTED}
		<p>Starts at:</p>
		<h3>{formatGameTime(game.gameTimeUTC, game.gameStatusText)}</h3>
	{:else}
		<h3>{game.gameStatusText}</h3>
	{/if}
	<!-- <GameOdds gameOdds={gameOdds} /> -->
</div>

<style>
	.nba-today-gamestatus {
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		gap: 0.25rem;
		text-wrap: balance;
		text-align: center;
		position: relative;
		height: 100%;

		& p {
			font-size: 0.75rem;
			font-weight: 100;
		}

		& h3 {
			font-size: 1rem;
		}
	}
</style>
