// client/src/app/(pages)/nba/_components/games-scores/GamesToday.tsx
import { GameStatus } from "@/lib/utils/enums/nba";
import "./GamesToday.css";
import NbaGame from "./NbaGame";
import { getTodaysGames } from "@/lib/api/nbaAPi";
import { TodaysGamesResponse } from "@/lib/utils/types/nba";

export default async function GamesToday() {
  const gamesToday: TodaysGamesResponse = await getTodaysGames();

  if (!gamesToday) {
    return (
      <section className="nba-today-scoreboard">
        <p>No games today.</p>
      </section>
    );
  }

  return (
    <section className="nba-today-scoreboard">
      {gamesToday.games.map((game) => (
        <NbaGame key={game.gameId} game={game} />
      ))}
    </section>
  );
}

// client/src/routes/nba/components/GamesToday.svelte
<script lang="ts">
	import type { NbaGame } from '$lib/types/nba';
	import ScoreboardGame from './ScoreboardGame.svelte';

	let { data }: { data: NbaGame[] } = $props();
</script>

<section class="nba-today-scoreboard">
	{#if data.length > 0}
		{#each data as game (game.gameId)}
			<ScoreboardGame {game} />
		{/each}
	{:else}
		<p>No games today.</p>
	{/if}
</section>

<style>
	.nba-today-scoreboard {
		display: grid;
		grid-template-columns: repeat(auto-fill, minmax(min(100%, 400px), 1fr));
		gap: 1rem;
	}
</style>
