// client/src/routes/nba/+page.svelte
<script lang="ts">
	import type { PageProps } from './$types';

	import Button from '$lib/components/ui/Button.svelte';
	import GamesToday from './components/GamesToday.svelte';

	import { MoveRight } from '@lucide/svelte';
	import Statbox from '$lib/components/nba/statbox/Statbox.svelte';

	let { data }: PageProps = $props();
</script>

<main class="nba-page">
	<section class="nba-today wrapper">
		<h1>NBA</h1>
		<h2>NBA Games & Scores</h2>
		<GamesToday data={data.games} />
	</section>
	<section class="nba-page-leaders wrapper">
		<h2>NBA Leaders</h2>
		<Statbox header="Points per game" stat="PTS" players={data.leaders} />
		<a href="/nba/leaderboards" class="nba-page-link">
			<Button class="btn-outline btn-with-icon">
				View All Leaderboards
				<MoveRight size={14} class="btn-icon" />
			</Button>
		</a>
	</section>
</main>

<style>
	.nba-page {
		display: flex;
		flex-direction: column;
		width: 100%;
		gap: 2rem;
		padding-bottom: 2rem;

		& h1 {
			align-self: center;
		}

		& h2 {
			font-size: 2rem;
			letter-spacing: 0;

			@media (max-width: 580px) {
				text-align: center;
			}
		}
	}

	.nba-today {
		padding-top: 2rem;
	}

	.nba-today,
	.nba-page-leaders {
		display: flex;
		flex-direction: column;
		gap: 1rem;
	}

	.nba-page-link {
		width: max-content;
	}
</style>

// client/src/app/(pages)/nba/page.tsx
import "./nba.css";
import LeadersBox from "./_components/statbox/StatBox";
import Link from "next/link";
import Button from "@/components/ui/Button";
import { MoveRight } from "lucide-react";
import NbaGame from "./_components/games-scores/NbaGame";
import GamesToday from "./_components/games-scores/GamesToday";

export default function Nba() {
  return (
    <main className="nba-page">
      <section className="nba-today wrapper">
        <h3>NBA Games & Scores</h3>
        <GamesToday />
      </section>
      <section className="nba-page-leaders wrapper">
        <h3>NBA Leaders</h3>
        <LeadersBox header="Points per game" stat="PTS" />
        <Link href="/nba/leaders" className="nba-page-link">
          <Button className="btn-outline btn-with-icon">
            View All Leaderboards
            <MoveRight size={14} className="btn-icon" />
          </Button>
        </Link>
      </section>
    </main>
  );
}
