// client/src/lib/components/layout/Navbar/Navbar.svelte
<script lang="ts">
	import Button from '$lib/components/ui/Button.svelte';
	import NavLinks from './NavLinks.svelte';
</script>

<nav>
	<a href="/" class="nav-logo">
		<h4>Ropsit</h4>
	</a>
	<NavLinks />
	<div class="nav-buttons">
		<Button class="btn-outline">Login</Button>
		<Button class="btn-cta">Sign Up</Button>
	</div>
</nav>

<style>
	.nav-buttons {
		display: flex;
		gap: 1rem;
		height: 2.5rem;

		& :global(button) {
			padding: 0.25rem 1.5rem;
		}
	}
</style>

// client/src/components/layout/Navbar.tsx
"use client";

import "./Navbar.css";
import Link from "next/link";
import Button from "../ui/Button";
import { usePathname } from "next/navigation";

export default function Navbar() {
  const path = usePathname();

  return (
    <nav>
      <Link href="/" className="nav-logo">
        <h4>Ropsit</h4>
      </Link>
      <ul className="nav-links">
        <li>
          <Link href="/nba" className={path === "/nba" ? "active" : ""}>
            NBA
          </Link>
        </li>
      </ul>
      <div className="nav-buttons">
        <Button className="btn-outline">Login</Button>
        <Button className="btn-cta">Sign Up</Button>
      </div>
    </nav>
  );
}
