// client/src/lib/components/nba/statbox/StatboxHeaders.svelte
<script lang="ts">
	import { formatColumnName } from '$lib/utils/format';

	let { columns }: { columns: readonly string[] } = $props();
</script>

<thead>
	<tr>
		<th scope="col">name</th>
		{#each columns as header (header)}
			<th scope="col">{formatColumnName(header)}</th>
		{/each}
	</tr>
</thead>

// client/src/app/(pages)/nba/_components/statbox/StatBoxHeaders.tsx
import { formatColumnName } from "@/lib/utils/format";

type StatBoxHeadersProps = {
  columns: readonly string[];
};

export default function StatBoxHeaders({ columns }: StatBoxHeadersProps) {
  return (
    <thead>
      <tr>
        <th scope="col">name</th>
        <th scope="col">team</th>
        <th scope="col">gp</th>
        <th scope="col">min</th>
        {columns.map((stat) => (
          <th scope="col" key={stat}>
            {formatColumnName(stat)}
          </th>
        ))}
      </tr>
    </thead>
  );
}
