// client/src/components/ui/Button.tsx
import "./Button.css";
import { ButtonHTMLAttributes, ReactNode } from "react";

type ButtonProps = {
  children: ReactNode;
  type?: "button" | "submit" | "reset";
} & ButtonHTMLAttributes<HTMLButtonElement>;

export default function Button({
  children,
  type = "button",
  ...props
}: ButtonProps) {
  return (
    <button type={type} {...props}>
      {children}
    </button>
  );
}

// sveltekit-client/src/lib/components/ui/Button.svelte
<script lang="ts">
	import './Button.css';
	import type { HTMLButtonAttributes } from 'svelte/elements';

	type ButtonProps = {
		type?: 'button' | 'submit' | 'reset';
	} & HTMLButtonAttributes;

	let { children, type = 'button', class: className = '', ...rest }: ButtonProps = $props();
</script>

<button {type} class={className} {...rest}>
	{@render children?.()}
</button>
