// sveltekit-client/src/lib/components/nba/statbox/Statbox.svelte
<script lang="ts">
	import './Statbox.css';
	import { STATBOX_COLUMNS, type StatType } from '$lib/constants/nba';
	import type { LeaderData } from '$lib/types/nba';
	import StatboxHeaders from './StatboxHeaders.svelte';
	import StatboxRow from './StatboxRow.svelte';

	let {
		header,
		stat,
		players = []
	}: { header: string; stat: StatType; players: LeaderData[typeof stat] } = $props();

	const columns = $derived(STATBOX_COLUMNS[stat]);
</script>

<section class="leaders-box wrapper">
	<h3>{header}</h3>
	<div class="table-wrapper">
		<table aria-label={`NBA ${header} leaders for 2025-2026 season`}>
			<StatboxHeaders {columns} />
			<tbody>
				{#each players as player (player.PLAYER_ID)}
					<StatboxRow {player} {columns} />
				{/each}
			</tbody>
		</table>
	</div>
</section>

// client/src/app/(pages)/nba/_components/StatBox.tsx
import "./StatBox.css";
import { getLeaders } from "@/lib/api/nbaAPi";
import StatBoxHeaders from "./StatBoxHeaders";
import StatBoxRow from "./StatBoxRow";
import type { LeaderData } from "@/lib/utils/types/nba";
import {
  LEADER_COLUMNS,
  type StatType,
} from "@/lib/utils/constants/leaderColumns";

type StatBoxProps = {
  header: string;
  stat: StatType;
};

export default async function StatBox({ header, stat }: StatBoxProps) {
  const res = await getLeaders(stat);
  const players: LeaderData[typeof stat] = res?.data || [];

  const columns = LEADER_COLUMNS[stat];

  return (
    <section className="leaders-box wrapper">
      <h2>{header}</h2>
      <div className="table-wrapper">
        <table aria-label={`NBA ${header} leaders for 2025-2026 season`}>
          <StatBoxHeaders columns={columns} />
          <tbody>
            {players.map((player) => (
              <StatBoxRow
                key={player.PLAYER_ID}
                player={player}
                columns={columns}
              />
            ))}
          </tbody>
        </table>
      </div>
    </section>
  );
}
